version: '3.6'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: db-server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: passW0rd
      MSSQL_PID: Express
